# Configuration file for running the tests. This will be assumed defaults,
# passed arguements to scripts will replace the value for that specific run of
# that script.
# So the order of precedence:
# specified arguments script calls > config values > script defaults (if any).
# Not all values are used here by the scripts.

# Hardware constants
#cores: 1 # If empty/null/None the maximum number of cores available will be used
#threads: lol this is Python.

# Random Seeds file
random_seeds_file:  'random_seeds_count-10000.txt'

output_dir: 'results/'


# Predictive Models evaluation variables.

n_nested_loop_count: 10
k_folds: 10

# annotated datasets to be used, and their respective predictive models
datasets:
    # Truth Inference Sruvey 2017
    # Comparison of Bayesian Models of Annotation 2018
    # Miscellaneous
    

# Truth inference models to be tested
truth_inference:
    # TODO state full name of models so its clear which is which.
    # If any model is not a string, but a dict, then that dict may contain the filepath to the dataset if different from default.
    models:
        # Non-Probablistic
        - majority_vote
        - mean  
        - median
        # Comparison of Bayesian Models of Annotation 2018
        - multinomial
        - dawid_skene
        - hier_dawid_skene
        - item_diff
        - log_rnd_eff
        - MACE
        # Truth Inference Survey 2017 (those not included above)
        - ZenCrowd
        - GLAD
        - minimax
        - BCC
        - CBCC
        - LFC
        - LFC-N
        - CATD
        - PM
        - Multi
        - KOS
        - VI-BP
        - VI-MF
        # Multi-Class Ground Truth Inference in Crowdsourcing with Clustering 2016
        - spectral_dawid_skene
        - GTIC # Ground Truth Inference using Clustering

# Metrics to be tested and used in evaluating models
metrics:
    any:
        - wasserstein_distance # Earth Mover's Distance
    regression:
        - MAE
        - RMSE
    classification:
        - accuracy
        - f1_score
        - confusion_matrix
